language: go

sudo: false

go:
  - 1.8

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -cover ./... -covermode=atomic -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
